import os
import pandas as pd
import gspread
from google.oauth2.service_account import Credentials
import json
import logging
import time
from gspread.exceptions import APIError

# Set up logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

MAX_RETRIES = 3
RETRY_DELAY = 5  # seconds

class GoogleSheetsPublisher:
    def __init__(self, credentials_json_string, spreadsheet_id, worksheet_name=None):
        """
        Initialize the Google Sheets publisher.

        Args:
            credentials_json_string: JSON string of service account credentials.
            spreadsheet_id: The Google Sheets spreadsheet ID.
            worksheet_name: Worksheet tab name to update; defaults to first sheet if None.
        """
        self.spreadsheet_id = spreadsheet_id
        self.worksheet_name = worksheet_name

        # Parse credentials and authorize client
        credentials_dict = json.loads(credentials_json_string)
        self.credentials = Credentials.from_service_account_info(
            credentials_dict,
            scopes=[
                'https://www.googleapis.com/auth/spreadsheets',
                'https://www.googleapis.com/auth/drive'
            ]
        )
        self.gc = gspread.authorize(self.credentials)
        logger.info("Google Sheets client authorized successfully.")

    def clear_and_update_sheet(self, csv_file_path):
        """
        Clear the worksheet and upload CSV data in bulk.
        CLEAN VERSION: No metadata added that could be picked up as products.

        Args:
            csv_file_path: Path to CSV file containing data.
        
        Returns:
            bool: True on success, False on failure.
        """
        try:
            logger.info(f"Opening spreadsheet ID: {self.spreadsheet_id}")
            spreadsheet = self.gc.open_by_key(self.spreadsheet_id)

            # Get or create worksheet
            if self.worksheet_name:
                try:
                    worksheet = spreadsheet.worksheet(self.worksheet_name)
                    logger.info(f"Found existing worksheet: '{self.worksheet_name}'")
                except gspread.WorksheetNotFound:
                    worksheet = spreadsheet.add_worksheet(title=self.worksheet_name, rows=1000, cols=50)
                    logger.info(f"Created new worksheet: '{self.worksheet_name}'")
            else:
                worksheet = spreadsheet.sheet1
                logger.info(f"Using first worksheet: '{worksheet.title}'")

            # Read CSV data into DataFrame
            logger.info(f"Reading CSV file: {csv_file_path}")
            df = pd.read_csv(csv_file_path)
            df.fillna('', inplace=True)  # Replace NaNs with empty strings

            # Clear existing worksheet content
            logger.info("Clearing existing worksheet content...")
            worksheet.clear()

            # Prepare data: header + rows ONLY (no metadata)
            data_to_upload = [df.columns.tolist()] + df.values.tolist()
            total_rows = len(data_to_upload)
            total_cols = len(df.columns)

            logger.info(f"Uploading {total_rows} rows and {total_cols} columns to Google Sheets...")
            logger.info("CLEAN MODE: No metadata will be added to prevent Merchant Center conflicts")

            # Retry wrapper for worksheet update
            for attempt in range(1, MAX_RETRIES + 1):
                try:
                    worksheet.update(
                        range_name=f'A1:{chr(64 + total_cols)}{total_rows}',
                        values=data_to_upload,
                        value_input_option='RAW'
                    )
                    logger.info("Data upload succeeded - CLEAN feed with no metadata interference")
                    break
                except APIError as e:
                    logger.error(f"APIError on attempt {attempt} of data upload: {e}")
                    if attempt == MAX_RETRIES:
                        raise
                    logger.info(f"Retrying in {RETRY_DELAY} seconds...")
                    time.sleep(RETRY_DELAY)

            # NO METADATA SECTION - This was causing Merchant Center to treat metadata as products!
            # The following section has been REMOVED to prevent merchant feed conflicts:
            # - Last Updated timestamp
            # - Total Products count  
            # - Generated By text
            # These were being interpreted as product data by Google Merchant Center

            logger.info(f"✅ Successfully updated Google Sheets with {len(df)} products (CLEAN VERSION)")
            logger.info("🚨 IMPORTANT: No metadata added to prevent Merchant Center conflicts")
            return True

        except Exception as e:
            logger.error(f"❌ Error updating Google Sheets: {e}")
            return False

    def append_to_sheet(self, csv_file_path):
        """
        Append rows from CSV to existing worksheet.
        CLEAN VERSION: Only appends actual product data.

        Args:
            csv_file_path: Path to CSV file containing data to append.
        
        Returns:
            bool: True on success, False on failure.
        """
        try:
            spreadsheet = self.gc.open_by_key(self.spreadsheet_id)
            worksheet = spreadsheet.worksheet(self.worksheet_name)

            df = pd.read_csv(csv_file_path)
            data_to_append = df.values.tolist()

            worksheet.append_rows(data_to_append, value_input_option='RAW')

            logger.info(f"✅ Successfully appended {len(df)} products to Google Sheets (CLEAN VERSION)")
            return True

        except Exception as e:
            logger.error(f"❌ Error appending to Google Sheets: {e}")
            return False


def main():
    SPREADSHEET_ID = os.getenv('SPREADSHEET_ID', "1aNtP8UJyy8sDYf3tPpCAZt-zMMHwofjpyEqrN9b1bJI")
    CSV_FILE_PATH = os.getenv('FEED_FILE', "google_feed/google_merchant_feed_fixed.csv")
    WORKSHEET_NAME = os.getenv('WORKSHEET_NAME', "google_merchant_feed")

    credentials_json = os.getenv('GOOGLE_SHEETS_CREDENTIALS')
    if not credentials_json:
        logger.error("❌ GOOGLE_SHEETS_CREDENTIALS environment variable not found.")
        return False

    if not os.path.exists(CSV_FILE_PATH):
        logger.error(f"❌ CSV file not found: {CSV_FILE_PATH}")
        return False

    publisher = GoogleSheetsPublisher(
        credentials_json_string=credentials_json,
        spreadsheet_id=SPREADSHEET_ID,
        worksheet_name=WORKSHEET_NAME
    )

    success = publisher.clear_and_update_sheet(CSV_FILE_PATH)

    if success:
        logger.info("🎉 Google Sheets update completed successfully! (CLEAN VERSION)")
        logger.info("🚨 No metadata added to prevent Merchant Center conflicts")
        print(f"📊 Updated spreadsheet: https://docs.google.com/spreadsheets/d/{SPREADSHEET_ID}")
        print("✅ Feed is now CLEAN - only product data, no metadata interference")
        return True
    else:
        logger.error("💥 Google Sheets update failed!")
        return False


if __name__ == "__main__":
    main()
