name: Crawl and Generate Product Feed

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 6 * * *'  # Daily at 6 AM UTC

jobs:
  crawl_and_generate_feed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Crawler Script
        run: python crawler.py

      - name: Run Feed Generator Script
        run: python product_feed_generator.py

      - name: Upload CSV and XML Feed
        uses: actions/upload-artifact@v2
        with:
          name: product-feeds
          path: |
            product_feed.csv
            product_feed.xml
