name: Generate Product Feed

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run crawler
        run: python crawler.py

      - name: Run product feed generator
        run: python product_feed_generator.py

      - name: Upload product_feed.csv
        uses: actions/upload-artifact@v2
        with:
          name: product_feed
          path: product_feed.csv

      - name: Upload product_feed.json
        uses: actions/upload-artifact@v2
        with:
          name: product_feed_json
          path: product_feed.json
