name: Generate Product Feed

on:
  workflow_dispatch:
  push:
    paths:
      - '**.py'
      - 'requirements.txt'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run feed generator
        run: |
          python crawler.py
          python product_feed_generator.py

      - name: Upload CSV Output
        uses: actions/upload-artifact@v3
        with:
          name: product_feed_csv
          path: google_feed/product_feed.csv

      - name: Upload JSON Backup
        uses: actions/upload-artifact@v3
        with:
          name: product_feed_json
          path: google_feed/product_feed.json
